"""Ajustes rápidos del prototipo."""

ANCHO_PANTALLA = 960
ALTO_PANTALLA = 540
FPS = 60
TIEMPO_BUSQUEDA_SEGUNDOS = 50
CANTIDAD_PUERTAS_SALA_1 = 4
CANTIDAD_PUERTAS_SALA_2 = 3

TECLA_INTERACCION = "E"
VELOCIDAD_JUGADOR = 220